"""관통프로젝트 Modbus 주소 맵 공통 정의.

이 파일은 mock_server.py, register_client.py, 이후 ROS2 modbus_bridge_node가
같은 coil/register 주소를 공유하기 위한 단일 기준이다.

주의:
- 주소는 현재 pymodbus가 사용하는 0-base address 기준으로 둔다.
- 실제 PLC 문서가 1-base 주소로 표기되어 있으면 장비 명세 확인 후 여기에서
  한 번만 조정하고, 각 client/server 파일에는 주소 보정 로직을 흩뿌리지 않는다.
"""

from __future__ import annotations

# Coil commands
CO_CMD_START = 0
CO_CMD_STOP = 1
CO_CMD_PAUSE = 2
CO_CMD_RESET = 3
CO_CMD_ACK_ALARM = 4
CO_CMD_CONVEYOR_RUN = 5
CO_CMD_CONVEYOR_STOP = 6
CO_CMD_MANUAL_MODE = 7

# Discrete inputs
DI_SENSOR_INFEED = 0
DI_SENSOR_PICK_ZONE = 1
DI_SENSOR_PACKAGING_ZONE = 2
DI_SENSOR_OUTFEED = 3
DI_ESTOP = 4
DI_DOOR_OPEN = 5

# Holding registers: process/common state
HR_PROCESS_STATE = 100
HR_PROCESS_SUBSTATE = 101
HR_COMMAND_SEQ = 102
HR_LAST_ACK_SEQ = 103
HR_ERROR_CODE = 104
HR_WARN_CODE = 105
HR_HEARTBEAT_PC = 106
HR_HEARTBEAT_PLC = 107

# Holding registers: device state
HR_DOBOT_STATE = 110
HR_CONVEYOR_STATE = 111
HR_CAMERA_STATE = 112
HR_TURTLEBOT_STATE = 113
HR_ROBODK_STATE = 114
HR_ROBODK_LAST_CMD = 115
HR_ROBODK_LAST_ACK_SEQ = 116
HR_ROBODK_ERROR_CODE = 117

# Holding registers: counters / conveyor / manual operation
HR_TARGET_COUNT_TOTAL = 120
HR_TARGET_COUNT_DONE = 121
HR_TARGET_COUNT_NG = 122
HR_CONVEYOR_SPEED_SET = 130
HR_CONVEYOR_SPEED_ACTUAL = 131
HR_MANUAL_COMMAND_CODE = 140
HR_MANUAL_COMMAND_ARG0 = 141
HR_MANUAL_COMMAND_ARG1 = 142
HR_OPERATION_MODE = 150

# Input registers
IR_SENSOR_DISTANCE_MM = 200
IR_CYCLE_TIME_MS = 201
IR_ALARM_ACTIVE_CODE = 202
IR_BOARD_TEMPERATURE = 203

COMMAND_COILS = [
    CO_CMD_START,
    CO_CMD_STOP,
    CO_CMD_PAUSE,
    CO_CMD_RESET,
    CO_CMD_ACK_ALARM,
    CO_CMD_CONVEYOR_RUN,
    CO_CMD_CONVEYOR_STOP,
    CO_CMD_MANUAL_MODE,
]


class RegisterMap:
    """기존 코드의 RegisterMap.HR_* 접근을 유지하기 위한 호환 래퍼."""

    # Coil commands
    CO_CMD_START = CO_CMD_START
    CO_CMD_STOP = CO_CMD_STOP
    CO_CMD_PAUSE = CO_CMD_PAUSE
    CO_CMD_RESET = CO_CMD_RESET
    CO_CMD_ACK_ALARM = CO_CMD_ACK_ALARM
    CO_CMD_CONVEYOR_RUN = CO_CMD_CONVEYOR_RUN
    CO_CMD_CONVEYOR_STOP = CO_CMD_CONVEYOR_STOP
    CO_CMD_MANUAL_MODE = CO_CMD_MANUAL_MODE

    # Discrete inputs
    DI_SENSOR_INFEED = DI_SENSOR_INFEED
    DI_SENSOR_PICK_ZONE = DI_SENSOR_PICK_ZONE
    DI_SENSOR_PACKAGING_ZONE = DI_SENSOR_PACKAGING_ZONE
    DI_SENSOR_OUTFEED = DI_SENSOR_OUTFEED
    DI_ESTOP = DI_ESTOP
    DI_DOOR_OPEN = DI_DOOR_OPEN

    # Holding registers
    HR_PROCESS_STATE = HR_PROCESS_STATE
    HR_PROCESS_SUBSTATE = HR_PROCESS_SUBSTATE
    HR_COMMAND_SEQ = HR_COMMAND_SEQ
    HR_LAST_ACK_SEQ = HR_LAST_ACK_SEQ
    HR_ERROR_CODE = HR_ERROR_CODE
    HR_WARN_CODE = HR_WARN_CODE
    HR_HEARTBEAT_PC = HR_HEARTBEAT_PC
    HR_HEARTBEAT_PLC = HR_HEARTBEAT_PLC
    HR_DOBOT_STATE = HR_DOBOT_STATE
    HR_CONVEYOR_STATE = HR_CONVEYOR_STATE
    HR_CAMERA_STATE = HR_CAMERA_STATE
    HR_TURTLEBOT_STATE = HR_TURTLEBOT_STATE
    HR_ROBODK_STATE = HR_ROBODK_STATE
    HR_ROBODK_LAST_CMD = HR_ROBODK_LAST_CMD
    HR_ROBODK_LAST_ACK_SEQ = HR_ROBODK_LAST_ACK_SEQ
    HR_ROBODK_ERROR_CODE = HR_ROBODK_ERROR_CODE
    HR_TARGET_COUNT_TOTAL = HR_TARGET_COUNT_TOTAL
    HR_TARGET_COUNT_DONE = HR_TARGET_COUNT_DONE
    HR_TARGET_COUNT_NG = HR_TARGET_COUNT_NG
    HR_CONVEYOR_SPEED_SET = HR_CONVEYOR_SPEED_SET
    HR_CONVEYOR_SPEED_ACTUAL = HR_CONVEYOR_SPEED_ACTUAL
    HR_MANUAL_COMMAND_CODE = HR_MANUAL_COMMAND_CODE
    HR_MANUAL_COMMAND_ARG0 = HR_MANUAL_COMMAND_ARG0
    HR_MANUAL_COMMAND_ARG1 = HR_MANUAL_COMMAND_ARG1
    HR_OPERATION_MODE = HR_OPERATION_MODE

    # Input registers
    IR_SENSOR_DISTANCE_MM = IR_SENSOR_DISTANCE_MM
    IR_CYCLE_TIME_MS = IR_CYCLE_TIME_MS
    IR_ALARM_ACTIVE_CODE = IR_ALARM_ACTIVE_CODE
    IR_BOARD_TEMPERATURE = IR_BOARD_TEMPERATURE


__all__ = [
    "RegisterMap",
    "COMMAND_COILS",
    "CO_CMD_START",
    "CO_CMD_STOP",
    "CO_CMD_PAUSE",
    "CO_CMD_RESET",
    "CO_CMD_ACK_ALARM",
    "CO_CMD_CONVEYOR_RUN",
    "CO_CMD_CONVEYOR_STOP",
    "CO_CMD_MANUAL_MODE",
    "DI_SENSOR_INFEED",
    "DI_SENSOR_PICK_ZONE",
    "DI_SENSOR_PACKAGING_ZONE",
    "DI_SENSOR_OUTFEED",
    "DI_ESTOP",
    "DI_DOOR_OPEN",
    "HR_PROCESS_STATE",
    "HR_PROCESS_SUBSTATE",
    "HR_COMMAND_SEQ",
    "HR_LAST_ACK_SEQ",
    "HR_ERROR_CODE",
    "HR_WARN_CODE",
    "HR_HEARTBEAT_PC",
    "HR_HEARTBEAT_PLC",
    "HR_DOBOT_STATE",
    "HR_CONVEYOR_STATE",
    "HR_CAMERA_STATE",
    "HR_TURTLEBOT_STATE",
    "HR_ROBODK_STATE",
    "HR_ROBODK_LAST_CMD",
    "HR_ROBODK_LAST_ACK_SEQ",
    "HR_ROBODK_ERROR_CODE",
    "HR_TARGET_COUNT_TOTAL",
    "HR_TARGET_COUNT_DONE",
    "HR_TARGET_COUNT_NG",
    "HR_CONVEYOR_SPEED_SET",
    "HR_CONVEYOR_SPEED_ACTUAL",
    "HR_MANUAL_COMMAND_CODE",
    "HR_MANUAL_COMMAND_ARG0",
    "HR_MANUAL_COMMAND_ARG1",
    "HR_OPERATION_MODE",
    "IR_SENSOR_DISTANCE_MM",
    "IR_CYCLE_TIME_MS",
    "IR_ALARM_ACTIVE_CODE",
    "IR_BOARD_TEMPERATURE",
]
