# High-level cell command.
# process_manager_node 또는 dashboard가 사용한다.

uint8 CMD_START=1
uint8 CMD_STOP=2
uint8 CMD_PAUSE=3
uint8 CMD_RESET=4
uint8 CMD_ACK_ALARM=5
uint8 CMD_CONVEYOR_RUN=6
uint8 CMD_CONVEYOR_STOP=7
uint8 CMD_MANUAL_MODE=8

uint8 command
uint16 command_seq
int32 arg0
int32 arg1
---
bool accepted
uint16 last_ack_seq
uint16 error_code
string message
